server:
  port: 9080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xiao512
    url: jdbc:mysql://localhost:3306/bbx_test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: DatebookHikariCP
mybatis:
  type-aliases-package: com.technology.pojo
  mapper-locations: classpath:mappers/*.xml

# 日志
logging:
  pattern:
    console: "%d - %msg%n"
  file: /var/log/info.log
  level:
    com.technology: debug