# 开发环境配置
server:
  port: 9081


mq:
  env: dev

log:
  user:
    queue:
      name: ${mq.env}.log.user.queue
    exchange:
      name: ${mq.env}.log.user.exchange
    routing:
      key:
        name: ${mq.env}.log.user.routing.key
mail:
  queue:
    name: ${mq.env}.mail.queue
  exchange:
    name: ${mq.env}.mail.exchange
  routing:
    key:
      name: ${mq.env}.mail.routing.key

user:
  order:
    queue:
      name: ${mq.env}.user.order.queue
    exchange:
      name: ${mq.env}.user.order.exchange
    routing:
      key:
        name: ${mq.env}.user.order.routing.key
spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: test
  datasource:
    master:
      password: xiao512
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://bbx-testdb-out.mysql.rds.aliyuncs.com:3306/bbx_test
      username: bbx_root
      password: LHBbx#2017@15