# 开发环境配置
server:
  port: 9081

mq:
  env: dev

log:
  user:
    queue:
      name: ${mq.env}.log.user.queue
    exchange:
      name: ${mq.env}.log.user.exchange
    routing:
      key:
        name: ${mq.env}.log.user.routing.key
mail:
  queue:
    name: ${mq.env}.mail.queue
  exchange:
    name: ${mq.env}.mail.exchange
  routing:
    key:
      name: ${mq.env}.mail.routing.key

user:
  order:
    queue:
      name: ${mq.env}.user.order.queue
    exchange:
      name: ${mq.env}.user.order.exchange
    routing:
      key:
        name: ${mq.env}.user.order.routing.key